/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#00451b",
        "on-secondary-container": "#663500",
        "surface-container-highest": "#d3e4fe",
        "primary-container": "#0d5c4d",
        "on-primary-fixed": "#00201a",
        "surface-container": "#e5eeff",
        "secondary": "#904d00",
        "outline-variant": "#bfc9c4",
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline": "#6f7975",
        "tertiary-container": "#005f28",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#8fd4c1",
        "secondary-fixed-dim": "#ffb77d",
        "error": "#ba1a1a",
        "primary": "#004337",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#8dd2bf",
        "primary-fixed": "#aaf0dc",
        "secondary-container": "#fe932c",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#6e3900",
        "on-tertiary-fixed": "#002109",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#005143",
        "on-surface-variant": "#3f4945",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "surface-tint": "#21695a",
        "on-secondary-fixed": "#2f1500",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#8fd4c1",
        "on-tertiary-fixed-variant": "#005322",
        "tertiary-fixed": "#66ff8e",
        "on-surface": "#0b1c30",
        "tertiary-fixed-dim": "#3de273",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "secondary-fixed": "#ffdcc3",
        "on-tertiary-container": "#3be172",
        "inverse-surface": "#213145",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin-sm": "1rem",
        "margin": "1.5rem",
        "margin-lg": "3rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "gutter-lg": "2rem",
      },
      fontFamily: {
        sans: ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "currency-stat": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Poppins", "Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
